// HR Pro System - Translations

const translations = {
    ar: {
        appName: 'HR Pro',
        loginTitle: 'تسجيل الدخول',
        username: 'اسم المستخدم',
        password: 'كلمة المرور',
        loginBtn: 'دخول',
        logout: 'خروج',
        dashboard: 'لوحة التحكم',
        employees: 'الموظفين',
        tasks: 'المهام',
        transfers: 'الانتقالات',
        custodies: 'العهد',
        finances: 'السلف',
        reports: 'التقارير',
        settings: 'الإعدادات',
        developer: 'عن المطور',
        totalEmployees: 'إجمالي الموظفين',
        activeTasks: 'المهام النشطة',
        pendingTransfers: 'انتقالات معلقة',
        totalFinances: 'إجمالي السلف',
        employeeStats: 'إحصائيات الموظفين',
        taskStats: 'إحصائيات المهام',
        addEmployee: 'إضافة موظف',
        editEmployee: 'تعديل موظف',
        name: 'الاسم',
        jobTitle: 'المسمى الوظيفي',
        department: 'القسم',
        actions: 'الإجراءات',
        edit: 'تعديل',
        delete: 'حذف',
        save: 'حفظ',
        cancel: 'إلغاء',
        todo: 'للقيام به',
        inProgress: 'قيد التنفيذ',
        done: 'منجز',
        addTask: 'إضافة مهمة',
        employee: 'الموظف',
        fromDepartment: 'من قسم',
        toDepartment: 'إلى قسم',
        date: 'التاريخ',
        status: 'الحالة',
        addTransfer: 'إضافة انتقال',
        item: 'العهد',
        assignedTo: 'مسؤول',
        addCustody: 'إضافة عهد',
        amount: 'المبلغ',
        addFinance: 'إضافة سلفة',
        employeesReport: 'تقرير الموظفين',
        tasksReport: 'تقرير المهام',
        financesReport: 'تقرير السلف',
        generalSettings: 'الإعدادات العامة',
        companyName: 'اسم الشركة',
        developerInfo: 'معلومات المطور',
        phone: 'الهاتف',
        email: 'البريد الإلكتروني',
        version: 'إصدار النظام'
    },
    en: {
        appName: 'HR Pro',
        loginTitle: 'Login',
        username: 'Username',
        password: 'Password',
        loginBtn: 'Login',
        logout: 'Logout',
        dashboard: 'Dashboard',
        employees: 'Employees',
        tasks: 'Tasks',
        transfers: 'Transfers',
        custodies: 'Custodies',
        finances: 'Finances',
        reports: 'Reports',
        settings: 'Settings',
        developer: 'Developer',
        totalEmployees: 'Total Employees',
        activeTasks: 'Active Tasks',
        pendingTransfers: 'Pending Transfers',
        totalFinances: 'Total Finances',
        employeeStats: 'Employee Statistics',
        taskStats: 'Task Statistics',
        addEmployee: 'Add Employee',
        editEmployee: 'Edit Employee',
        name: 'Name',
        jobTitle: 'Job Title',
        department: 'Department',
        actions: 'Actions',
        edit: 'Edit',
        delete: 'Delete',
        save: 'Save',
        cancel: 'Cancel',
        todo: 'To Do',
        inProgress: 'In Progress',
        done: 'Done',
        addTask: 'Add Task',
        employee: 'Employee',
        fromDepartment: 'From Department',
        toDepartment: 'To Department',
        date: 'Date',
        status: 'Status',
        addTransfer: 'Add Transfer',
        item: 'Item',
        assignedTo: 'Assigned To',
        addCustody: 'Add Custody',
        amount: 'Amount',
        addFinance: 'Add Finance',
        employeesReport: 'Employees Report',
        tasksReport: 'Tasks Report',
        financesReport: 'Finances Report',
        generalSettings: 'General Settings',
        companyName: 'Company Name',
        developerInfo: 'Developer Info',
        phone: 'Phone',
        email: 'Email',
        version: 'System Version'
    }
};

// Make translations available globally
window.translations = translations;
